# Generated by Django 5.1.2 on 2024-11-07 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrePublicationType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "DRE Publication Type",
                "verbose_name_plural": "DRE Publication Types",
            },
        ),
        migrations.CreateModel(
            name="DrePublication",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                ("part", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("body", models.TextField()),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dre.drepublicationtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "DRE Publication",
                "verbose_name_plural": "DRE Publications",
            },
        ),
    ]
