# Generated by Django 5.1.2 on 2024-11-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DreData",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                ("type", models.CharField(max_length=255)),
                ("part", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("body", models.TextField()),
            ],
            options={
                "db_table": "dre_data",
            },
        ),
    ]
